defaults:
  - dataset: base
  - dataset/split: rwrf_2022
  - dataset/var : cm
  - dataset/res: 10km
  - model/architecture: cm_10km
  - _self_

experiment:
  name: test

dtype: float64

hydra:
  job:
    config:
      override_dirname:
        kv_sep: '_'
        item_sep: '-'
        exclude_keys:
          - experiment.name
          - trainer
  run:
    dir: ./experiments/${experiment.name}/
  sweep:
    dir: ./experiments/${experiment.name}/
    subdir: ${hydra.job.override_dirname}