defaults:
  - dataset: base
  - dataset/split: rwrf_2022
  - dataset/var : cm
  - dataset/res: 4km
  - model/architecture: cm
  - _self_

experiment:
  name: test

dtype: float64

logger:
  _target_: lightning.pytorch.loggers.WandbLogger
  project: "DLAMP.cm"
  name: ${experiment.name}
  mode: offline
  save_dir: .
  log_model: False

hydra:
  job:
    config:
      override_dirname:
        kv_sep: '_'
        item_sep: '-'
        exclude_keys:
          - experiment.name
          - trainer
  run:
    dir: ./experiments/${experiment.name}/
  sweep:
    dir: ./experiments/${experiment.name}/
    subdir: ${hydra.job.override_dirname}