input_single:
  - sst
  - psfc
  - t2m
  - q2m
  - u10
  - v10
  - olr
  - sw
input_static:
  - landmask
  - terrain
  - latitude
  - longitude
input_upper:
  - z
  - u
  - v
  - t
  - qv
target:
  - qc
  - qr
  - qi
  - qs
  - qg

z_input:
  - 1000
  - 925
  - 850
  - 700
  - 600
  - 500
  - 400
  - 300
  - 250
  - 200
  - 150
  - 100
  - 50
z_target:
  - 1000
  - 975
  - 950
  - 925
  - 900
  - 875
  - 850
  - 825
  - 800
  - 775
  - 750
  - 700
  - 650
  - 600
  - 550
  - 500
  - 450
  - 400
  - 350
  - 300
  - 250
  - 225
  - 200
  - 175
  - 150
  - 125
  - 100
  - 70
  - 50
  - 30
  - 20